# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: benchmarking
      run: dotnet run -c Release --project Benchmarks/Benchmarks.csproj --exporters json
    - name: List Files
      uses: mirko-felice/list-files-action@v3.0.5
      with:
        repo: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: "."
        ext: ".json"
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Benchmarks.Md5VsSha256-report-full-compressed.json
     
